version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: geodjango
    environment:
      PYTHONDONTWRITEBYTECODE: "no-write"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tenochtitlan
      DB_USER: tlaloc
      DB_PASSWORD: passw0rd
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: python geodjango/manage.py runserver 0.0.0.0:8000
    restart: on-failure

  db:
    image: postgis/postgis:14-3.1-alpine
    environment:
      POSTGRES_DB: tenochtitlan
      POSTGRES_USER: tlaloc
      POSTGRES_PASSWORD: passw0rd
    expose:
      - 5432